{
 "title": "Ya IoT",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sensor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"temperature\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  {
   "title": "Sensor Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"humidity\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  {
   "title": "Sensor Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"battery_level\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  {
   "title": "Sensor Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"pressure\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  { "title": "Sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Socket Amperage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"amperage\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  {
   "title": "Socket Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"power\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  {
   "title": "Socket Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"voltage\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  { "title": "Lamps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Lamp Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"temperature_k\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  {
   "title": "Lamp Brightness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"brightness\"}",
     "legendFormat": "{{room}} | {{deviceName}}"
    }
   ]
  },
  { "title": "States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Scenario Status",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "ya_iot_scenarios", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Device Status",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "ya_iot_devices{stateInstance=\"on\"}",
     "legendFormat": "{{room}} {{deviceName}}"
    }
   ]
  }
 ]
}